jaffle_shop_cosmos:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "FIELDENGINEER"
      warehouse: "TINY_ROBOTS"
      database: "DEMO"
      schema: "FIELDENGINEER"
      threads: 4
      client_session_keep_alive: true
